name: terrarun
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-command:
    runs-on: runner01

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: initialize terraform
      run: |
        terraform init 

    - name: Performing refresh
      run: |
        terraform refresh

    - name: Apllying Configuration
      run: |
        bash -c 'terraform apply --auto-approve'

